defaultContentLanguage: "pt"
enableGitInfo: true
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
disableHugoGeneratorInject: true
disableKinds:
  - "taxonomy"
  - "taxonomyTerm"
  - "RSS"
  - "sitemap"
outputs:
  section:
    - html
    - json
googleAnalytics: "UA-116653569-1"
removePathAccents: true
metaDataFormat: "yaml"
blackfriday:
  smartypants: false
params:
  searchLimit: 12
languages:
  pt:
    languageCode: "pt-br"
    # baseURL: "https://pegabot.com.br"
    languageName: Português
    title: Pegabot
    weight: 1
    params:
      siteDescription: "O Pegabot verifica a atividade de uma conta em rede social e dá uma pontuação baseada na probabilidade dessa conta ser um bot. Maiores pontuações são mais bot-like."
      tagline: "Por mais transparência no uso de bots"
      email: pegabot@itsrio.org
      typeform: https://itsrio2.typeform.com/to/uGFw4zDc
      ogImage: "/pegabot-fb-img__pt.jpg"
      ogTitle: "Descubra se aquele perfil de rede social é bot"
  es:
    languageCode: "es-mx"
    # baseURL: "https://es.pegabot.com.br"
    languageName: Español
    title: AtrapaBot
    weight: 2
    params:
      siteDescription: "El AtrapaBot verifica la actividad de una determinada cuenta en la red social y le atribuye una puntuación basada en la probabilidad de que sea un bot. Las puntuaciones mayores son más bot-like."
      tagline: "Por una mayor transparencia en el uso de bots."
      email:
      typeform: https://itsrio2.typeform.com/to/uC2R0P
      ogImage: "/es/pegabot-fb-img__es.jpg"
      ogTitle: "Descubra las chances de que aquel perfil tan exitoso sea un bot."
