defaultContentLanguage: "pt"
enableGitInfo: true
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
disableHugoGeneratorInject: true
disableKinds:
  - "taxonomy"
  - "taxonomyTerm"
  - "RSS"
  - "sitemap"
outputs:
  section:
    - html
    - json
googleAnalytics: "UA-116653569-1"
languageCode: "pt-br"
removePathAccents: true
metaDataFormat: "yaml"

privacy:
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: true
  instagram:
    disable: false
    simple: true
  twitter:
    disable: false
    enableDNT: true
    simple: true
  vimeo:
    disable: false
    enableDNT: true
    simple: true
  youtube:
    disable: false
    privacyEnhanced: true

services:
  twitter:
    disableInlineCSS: true

blackfriday:
  smartypants: false
params:
  cookieDomain: ".pegabot.com.br"
  searchLimit: 12
languages:
  pt:
    languageCode: "pt-br"
    baseURL: "https://pegabot.com.br"
    languageName: Português
    title: Pegabot
    params:
      siteDescription: "O Pegabot verifica a atividade de uma conta em rede social e dá uma pontuação baseada na probabilidade dessa conta ser um bot. Maiores pontuações são mais bot-like."
      tagline: "Por mais transparência no uso de bots"
      email: pegabot@itsrio.org
      typeform: https://itsrio2.typeform.com/to/uGFw4zDc
      ogImage: "/pegabot-fb-img__pt.jpg"
      ogTitle: "Descubra se aquele perfil de rede social é bot"
      cookieContentHref: "https://www.serpro.gov.br/lgpd/menu/a-lgpd/o-que-muda-com-a-lgpd"
  es:
    languageCode: "es-mx"
    baseURL: "https://es.pegabot.com.br"
    languageName: Español
    title: AtrapaBot
    params:
      siteDescription: "El AtrapaBot verifica la actividad de una determinada cuenta en la red social y le atribuye una puntuación basada en la probabilidad de que sea un bot. Las puntuaciones mayores son más bot-like."
      tagline: "Por una mayor transparencia en el uso de bots."
      email:
      typeform: https://itsrio2.typeform.com/to/ucOsl1sP
      ogImage: "/es/pegabot-fb-img__es.jpg"
      ogTitle: "Descubra las chances de que aquel perfil tan exitoso sea un bot."
      cookieContentHref: "https://www.serpro.gov.br/lgpd/menu/a-lgpd/o-que-muda-com-a-lgpd"
