baseURL: "https://dev.pegabot.com.br"
languageCode: "pt-br"
title: "Pegabot"
defaultContentLanguage: "pt"
enableGitInfo: true
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
disableHugoGeneratorInject: true
disableKinds:
  - "section"
  - "taxonomy"
  - "taxonomyTerm"
  - "RSS"
  - "sitemap"
googleAnalytics: ""
languageCode: "pt-br"
metaDataFormat: "yaml"
params:
  siteDescription: "O Pegabot verifica a atividade de uma conta em rede social e dá uma pontuação baseada na probabilidade dessa conta ser um bot. Maiores pontuações são mais bot-like."
  tagline: "Por mais transparência no uso de bots"
languages:
  pt:
    params:
      siteDescription: "O Pegabot verifica a atividade de uma conta em rede social e dá uma pontuação baseada na probabilidade dessa conta ser um bot. Maiores pontuações são mais bot-like."
      tagline: "Por mais transparência no uso de bots"
