defaultContentLanguage: "pt"
enableGitInfo: true
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
disableHugoGeneratorInject: true
disableKinds:
  - "section"
  - "taxonomy"
  - "taxonomyTerm"
  - "RSS"
  - "sitemap"
googleAnalytics: "UA-116653569-1"
languageCode: "pt-br"
metaDataFormat: "yaml"
blackfriday:
  smartypants: false
params:
  siteDescription: "O Pegabot verifica a atividade de uma conta em rede social e dá uma pontuação baseada na probabilidade dessa conta ser um bot. Maiores pontuações são mais bot-like."
  tagline: "Por mais transparência no uso de bots"
languages:
  pt:
    languageCode: "pt-br"
    baseURL: "https://pegabot.com.br"
    languageName: Portuguese
    title: Pegabot
    params:
      siteDescription: "O Pegabot verifica a atividade de uma conta em rede social e dá uma pontuação baseada na probabilidade dessa conta ser um bot. Maiores pontuações são mais bot-like."
      tagline: "Por mais transparência no uso de bots"
  es:
    languageCode: "es-mx"
    baseURL: "https://atrapabot.org"
    languageName: Español
    title: Atrapabot
    params:
      siteDescription: "Atrapabot verifica la actividad de cuentas de Twitter y da una puntuación basada en la probabilidad de que esta cuenta sea un bot."
      tagline: "Por mais transparência no uso de bots"
