baseURL: ""
languageCode: "pt-br"
title: "pegaBots"
defaultContentLanguage: "pt"
disableRSS: true
enableGitInfo: true
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
disableKinds:
  - "section"
  - "taxonomy"
  - "taxonomyTerm"
  - "RSS"
  - "sitemap"
googleAnalytics: ""
languageCode: "pt-br"
metaDataFormat: "yaml"
