defaultContentLanguage: "pt"
enableGitInfo: true
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
disableHugoGeneratorInject: true
disableKinds:
  - "taxonomy"
  - "taxonomyTerm"
  - "RSS"
  - "sitemap"
outputs:
  section:
    - html
    - json
googleAnalytics: "UA-116653569-1"
languageCode: "pt-br"
metaDataFormat: "yaml"
blackfriday:
  smartypants: false
params:
  searchLimit: 12
languages:
  pt:
    languageCode: "pt-br"
    baseURL: "https://pegabot.com.br"
    languageName: Português
    title: Pegabot
    params:
      siteDescription: "O Pegabot verifica a atividade de uma conta em rede social e dá uma pontuação baseada na probabilidade dessa conta ser um bot. Maiores pontuações são mais bot-like."
      tagline: "Por mais transparência no uso de bots"
      email: pegabot@itsrio.org
      typeform: https://itsrio2.typeform.com/to/k9FHXq
      ogImage: "/pegabot-fb-img__pt.jpg"
      ogTitle: "Descubra se aquele perfil de rede social é bot"
  es:
    languageCode: "es-mx"
    baseURL: "https://es.pegabot.com.br"
    languageName: Español
    title: AtrapaBot
    params:
      siteDescription: "El AtrapaBot verifica la actividad de una determinada cuenta en la red social y le atribuye una puntuación basada en la probabilidad de que sea un bot. Las puntuaciones mayores son más bot-like."
      tagline: "Por una mayor transparencia en el uso de bots."
      email:
      typeform: https://itsrio2.typeform.com/to/uC2R0P
      ogImage: "/pegabot-fb-img__es.jpg"
      ogTitle: "Descubra las chances de que aquel perfil tan exitoso sea un bot."
  en:
    languageCode: "en-us"
    baseURL: "https://pegabot.com.br"
    languageName: English
    title: Bot Spotter
    params:
      siteDescription: "Bot Spotter verifies social media profiles and gives a score after an assessment of its activities, analysing the probability of the account being a bot. Highest scores are more bot-like."
      tagline: "For more transparency in the use of bots"
      email:
      typeform: https://itsrio2.typeform.com/to/k9FHXq
      ogImage: "/pegabot-fb-img.jpg"
      ogTitle: "Find out if a social media profile is a bot"
