backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  repo: AppCivico/pegabot
  site_domain: pegabot.com.br
  base_url: https://api.netlify.com
  auth_endpoint: auth
media_folder: "content/uploads"
public_folder: "/uploads"
locale: "pt"
sortableFields: ["commit_date", "title", "commit_author", "language"]
logo_url: /source/images/logotype.png
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
- name: "faq_pt"
  label: "Perguntas frequentes"
  label_singular: "Pergunta frequente"
  folder: "content/faq"
  # identifier_field: "slug"
  slug: "{{slug}}.{{language}}"
  preview_path: "/faq#{{slug}}"
  create: true
  extension: md
  view_filters:
  - label: "Português"
    field: language
    pattern: "pt"
  - label: "Español"
    field: language
    pattern: "en"
  fields:
  - {label: "Language", name: "language", widget: "select", options: ["es", "pt"]}
  - name: "title"
    label: "Título"
    widget: "string"
  - name: "slug"
    label: "Âncora"
    widget: "string"
    required: false
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"
