backend:
  name: github
  # @see https://www.netlifycms.org/docs/test-backend/
  # name: test-repo
  branch: dev # Branch to update (optional; defaults to master)
  repo: AppCivico/pegabot
  site_domain: dev.pegabot.com.br
  base_url: https://api.netlify.com
  auth_endpoint: auth
  squash_merges: true
  api_root: https://api.github.com
media_folder: "content/uploads"
public_folder: "uploads"
locale: "pt"
sortableFields: ["commit_date", "title", "commit_author", "language"]
logo_url: /assets/images/logos/logotype--no-text.png
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"


collections:
- name: "analysis"
  label: "Análises"
  label_singular: "Análise"
  folder: "content/analysis"
  slug: "{{slug}}.{{language}}"
  preview_path: "/analysis#{{slug}}"
  create: true
  extension: md
  view_filters:
  - label: "Português"
    field: language
    pattern: "pt"
  - label: "Español"
    field: language
    pattern: "en"
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - {label: "Draft?", name: "draft", widget: "boolean", default: false, required: false}
  - name: "title"
    label: "Título"
    widget: "string"
  - {label: "Slug", name: "slug", widget: "string", required: false}
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"
  - label: "Favorito"
    name: "bookmark"
    widget: "object"
    collapsed: true
    fields:
    - {label: "Título", name: "title", widget: "string"}
    - {label: "Trecho", name: "excerpt", widget: "string"}
    - {label: "Imagem", name: "src", widget: "image"}
    - {label: "Descrição", name: "alt", widget: "string"}
    - {label: "Legenda", name: "caption", widget: "string"}
    - label: "Link"
      name: "link"
      widget: "string"
      pattern:
      - '^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)?'
      - "Use a valid URL"
  - {name: "weight", valueType: "int", widget: "hidden", label: "Ordem", default: 1}
  - {label: "Show on home", name: "homepage", widget: "boolean", default: false}
  - {name: "layout", widget: "hidden", default: "none"}
  - {name: "type", widget: "hidden", default: "analysis"}


- name: bookmarks
  label: Favoritos
  slug: "{{slug}}"
  folder: "content/bookmarks"
  create: true
  delete: true
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - {label: "Draft?", name: "draft", widget: "boolean", default: false, required: false}
  - name: "title"
    label: "Título"
    widget: "hidden"
    default: "{{slug}}"
  - {label: "Slug", name: "slug", widget: "string", required: false}
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "author"
    label: "Autor(es)"
    widget: "string"
  - name: "imageSrc"
    label: "Imagem (.svg)"
    widget: "image"
  - label: "imageAlt"
    name: "Image description"
    widget: "string"
    required: false
  - label: "Link"
    name: "link"
    widget: "string"
    required: false
    pattern:
    - '^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)?'
    - "Use a valid URL"
  - {name: "layout", widget: "hidden", default: "none"}
  - {name: "type", widget: "hidden", default: "bookmark"}
  - {name: "weight", valueType: "int", widget: "hidden", label: "Ordem", default: 1, min: 0}


- name: "callToAction"
  label: "Chamadas"
  folder: "content/call-to-action"
  create: true
  delete: true
  slug: "{{slug}}"
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - {label: "Draft?", name: "draft", widget: "boolean", default: false, required: false}
  - name: "title"
    label: "Título"
    widget: "string"
    tagname: "h3"
  - {label: "Slug", name: "slug", widget: "string", required: false}
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "type"
    label: "type"
    widget: "hidden"
    default: "callToAction"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"
    required: false
  - {name: "layout", widget: "hidden", default: "none"}
  - {name: "type", widget: "hidden", default: "callToAction"}
  - {name: "weight", valueType: "int", widget: "hidden", label: "Ordem", default: 1, min: 0}


- name: "collaborate"
  label: "Chamadas a colaborar"
  folder: "content/collaborate"
  create: true
  delete: true
  slug: "{{slug}}"
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - {label: "Draft?", name: "draft", widget: "boolean", default: false, required: false}
  - name: "title"
    label: "Título"
    widget: "string"
    tagname: "h3"
  - {label: "Slug", name: "slug", widget: "string", required: false}
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "type"
    label: "type"
    widget: "hidden"
    default: "collaborate"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"
  - {label: "Menus", name: "menu", widget: "select", options: [{ label: "Top", value: "header" }, { label: "Bottom", value: "main" }]}
  - name: "weight"
    label: "Ordem"
    widget: "hidden"
    default: 1
    valueType: "int"
    min: 0
    required: false
  - name: "imageSrc"
    label: "Imagem"
    widget: "image"
  - name: "bottomImageSrc"
    label: "Imagem inferior"
    widget: "image"
  - label: "Link"
    name: "link"
    widget: "string"
    pattern:
    - '^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)?'
    - "Use a valid URL"


- name: "faq"
  label: "Perguntas frequentes"
  label_singular: "Pergunta frequente"
  folder: "content/faq"
  # identifier_field: "slug"
  slug: "{{slug}}.{{language}}"
  preview_path: "/faq#{{slug}}"
  create: true
  extension: md
  view_filters:
  - label: "Português"
    field: language
    pattern: "pt"
  - label: "Español"
    field: language
    pattern: "en"
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - {label: "Draft?", name: "draft", widget: "boolean", default: false, required: false}
  - name: "title"
    label: "Título"
    widget: "string"
  - {label: "Slug", name: "slug", widget: "string", required: false}
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"
  - {name: "weight", valueType: "int", label: "Ordem", default: 1, min: 0, required: false}
  - {name: "layout", widget: "hidden", default: "none"}
  - {name: "type", widget: "hidden", default: "faq"}


- name: "investigations"
  label: "Investigações"
  label_singular: "Investigação"
  folder: "content/investigations"
  slug: "{{slug}}.{{language}}"
  preview_path: "/investigations#{{slug}}"
  create: true
  extension: md
  view_filters:
  - label: "Português"
    field: language
    pattern: "pt"
  - label: "Español"
    field: language
    pattern: "en"
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - {label: "Draft?", name: "draft", widget: "boolean", default: false, required: false}
  - name: "title"
    label: "Título"
    widget: "string"
  - {label: "Slug", name: "slug", widget: "string", required: false}
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "file"
    label: "Arquivo para download"
    widget: "file"
  - {name: "weight", valueType: "int", label: "Ordem", default: 1, min: 0, required: false}
  - {name: "layout", widget: "hidden", default: "none"}
  - {name: "type", widget: "hidden", default: "investigations"}
  - {label: "Show on home", name: "homepage", widget: "boolean", default: false}

- name: "pages"
  label: "Páginas"
  folder: "content"
  slug: "{{slug}}.{{language}}"
  preview_path: "/{{slug}}"
  create: true
  extension: md
  view_filters:
  - label: "Português"
    field: language
    pattern: "pt"
  - label: "Español"
    field: language
    pattern: "en"
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - {label: "Draft?", name: "draft", widget: "boolean", default: false, required: false}
  - name: "title"
    label: "Título"
    widget: "string"
  - {label: "Slug", name: "slug", widget: "string"}
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"
  - {name: "layout", widget: "select", options:[ "analysis", "collaborate", "detailed", "faq", "results", "transparency", "about" ]}
  - name: menu
    label: Menu
    widget: "object"
    fields:
    - name: "header"
      label: "Header"
      widget: object
      fields:
      - name: name
        widget: string
    - name: "main"
      label: "Footer"
      widget: "object"
      fields:
      - name: name
        widget: string
  - {name: "weight", valueType: "int", label: "Ordem no menu", default: 1, min: 0}


- name: results
  label: "Seção de resultados"
  folder: "content/results"
  extension: md
  slug: "{{slug}}.{{language}}"
  view_filters:
  - label: "Português"
    field: language
    pattern: "pt"
  - label: "Español"
    field: language
    pattern: "en"
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - name: "title"
    label: "Título"
    widget: "string"
  - {label: "Slug", name: "slug", widget: "string", required: false}
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"
  - name: "figure"
    widget: "object"
    fields:
    - name: "src"
      widget: file
      required: true
    - name: "caption"
      label: "Legenda"
      widget: "string"
    - name: "alt"
      label: "Descrição"
      widget: "string"
      required: true
  - name: "weight"
    valueType: "int"
    label: "Ordem"
    widget: "hidden"
    default: 1
    min: 0
  - {name: "layout", widget: "select", options:[ "results", "none" ]}


# - name: supporters
#   label: "Apoiadores"
#   slug: "{{slug}}"
#   files:
#   - name: "supporters"
#     label: "Apoiadores"
#     file: "data/supporters.json"
#     fields:
#     - name: "title"
#       label: "Título"
#       widget: "string"
#     - name: "image"
#       label: "Logo (svg)"
#       widget: "image"
#     - name: "url"
#       label: "url"
#     - name: "weight"
#       valueType: "int"
#       label: "Ordem"
#       widget: "hidden"
#       default: 1
#       required: false
#       min: 0


- name: "transparency"
  label: "Transparência"
  folder: "content/transparency"
  slug: "{{slug}}.{{language}}"
  preview_path: "/transparency#{{slug}}"
  create: true
  extension: md
  view_filters:
  - label: "Português"
    field: language
    pattern: "pt"
  - label: "Español"
    field: language
    pattern: "en"
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - {label: "Draft?", name: "draft", widget: "boolean", default: false, required: false}
  - name: "title"
    label: "Título"
    widget: "string"
  - name: "slug"
    label: "Âncora"
    widget: "string"
    required: false
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"
  - {name: "weight", valueType: "int", widget: "hidden", label: "Ordem", default: 1, min: 0}
  - {label: "Show on home", name: "homepage", widget: "boolean", default: false}
  - {name: "layout", widget: "hidden", default: "none"}
