backend:
  name: github
  # @see https://www.netlifycms.org/docs/test-backend/
  # name: test-repo
  branch: dev # Branch to update (optional; defaults to master)
  repo: AppCivico/pegabot
  site_domain: dev.pegabot.com.br
  base_url: https://api.netlify.com
  auth_endpoint: auth
  squash_merges: true
  api_root: https://api.github.com
media_folder: "content/uploads"
public_folder: "uploads"
locale: "pt"
sortableFields: ["commit_date", "title", "commit_author", "language"]
logo_url: /images/logotype--no-text.png
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
- name: "faq"
  label: "Perguntas frequentes"
  label_singular: "Pergunta frequente"
  folder: "content/faq"
  # identifier_field: "slug"
  slug: "{{slug}}.{{language}}"
  preview_path: "/faq#{{slug}}"
  create: true
  extension: md
  view_filters:
  - label: "Português"
    field: language
    pattern: "pt"
  - label: "Español"
    field: language
    pattern: "en"
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - name: "title"
    label: "Título"
    widget: "string"
  - name: "slug"
    label: "Âncora"
    widget: "string"
    required: false
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"

- name: "analysis"
  label: "Análises"
  label_singular: "Análise"
  folder: "content/analysis"
  slug: "{{slug}}.{{language}}"
  preview_path: "/analysis#{{slug}}"
  create: true
  extension: md
  view_filters:
  - label: "Português"
    field: language
    pattern: "pt"
  - label: "Español"
    field: language
    pattern: "en"
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - name: "title"
    label: "Título"
    widget: "string"
  - name: "file"
    label: "Arquivo para download"
    widget: "file"
  - name: "slug"
    label: "Âncora"
    widget: "string"
    required: false
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"
  - label: "Favorito"
    name: "bookmark"
    widget: "object"
    collapsed: true
    fields:
    - {label: "Título", name: "title", widget: "string"}
    - {label: "Trecho", name: "excerpt", widget: "string"}
    - {label: "Imagem", name: "src", widget: "image"}
    - {label: "Descrição", name: "alt", widget: "string"}
    - {label: "Legenda", name: "caption", widget: "string"}
    - label: "Link"
      name: "link"
      widget: "string"
      pattern:
      - '^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)?'
      - "Use a valid URL"


- name: "investigations"
  label: "Investigações"
  label_singular: "Investigação"
  folder: "content/investigations"
  slug: "{{slug}}.{{language}}"
  preview_path: "/investigations#{{slug}}"
  create: true
  extension: md
  view_filters:
  - label: "Português"
    field: language
    pattern: "pt"
  - label: "Español"
    field: language
    pattern: "en"
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - name: "title"
    label: "Título"
    widget: "string"
  - name: "file"
    label: "Arquivo para download"
    widget: "file"
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"

- name: "transparency"
  label: "Transparência"
  folder: "content/transparency"
  slug: "{{slug}}.{{language}}"
  preview_path: "/transparency#{{slug}}"
  create: true
  extension: md
  view_filters:
  - label: "Português"
    field: language
    pattern: "pt"
  - label: "Español"
    field: language
    pattern: "en"
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - name: "title"
    label: "Título"
    widget: "string"
  - name: "slug"
    label: "Âncora"
    widget: "string"
    required: false
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"

- name: supporters
  label: "Apoiadores"
  slug: "{{slug}}"
  files:
  - name: "supporters"
    label: "Apoiadores"
    file: "data/supporters.json"
    fields:
    - name: "title"
      label: "Título"
      widget: "string"
    - name: "image"
      label: "Logo (svg)"
      widget: "image"
    - name: "url"
      label: "url"
    - name: "weight"
      label: "Ordem"
      default: 0

- name: bookmarks
  label: Favoritos
  slug: "{{slug}}"
  folder: "content/bookmarks"
  create: true
  delete: true
  fields:
  - name: "title"
    label: "Título"
    widget: "hidden"
    default: "{{slug}}"
  - name: "author"
    label: "Autor(es)"
    widget: "string"
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "image"
    label: "Imagem (.svg)"
    widget: "image"
  - name: "link"
    label: "Link"
    widget: "string"
    required: false

- name: "callToAction"
  label: "Chamadas"
  folder: "content/call-to-action"
  create: true
  delete: true
  slug: "{{slug}}"
  fields:
  - name: "title"
    label: "Título"
    widget: "string"
    tagname: "h3"
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "type"
    label: "type"
    widget: "hidden"
    default: "callToAction"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"
  - name: "weight"
    label: "Ordem"
    widget: "number"
    default: 1
    valueType: "int"
    min: 0
