backend:
  name: github
  # @see https://www.netlifycms.org/docs/test-backend/
  # name: test-repo
  branch: dev # Branch to update (optional; defaults to master)
  repo: AppCivico/pegabot
  site_domain: dev.pegabot.com.br
  base_url: https://api.netlify.com
  auth_endpoint: auth
  squash_merges: true
  api_root: https://api.github.com
media_folder: "content/uploads"
public_folder: "uploads"
publish_mode: editorial_workflow
squash_merges: true
locale: "pt"
sortable_fields: ["commit_date", "draft", "language", "title", "weight"]
logo_url: /assets/images/logos/logotype--no-text.png
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
editor:
  preview: false

collections:

- name: "pages"
  label: "Páginas"
  folder: "content"
  preview_path: "{{dirname}}/{{filename}}.{{extension}}"
  slug: "{{slug}}.{{language}}"
  format: frontmatter
  summary: "{{title}} ({{language}})"
  extension: "md"
  create: true
  view_filters:
  - {label: "Português", field: language, pattern: "pt"}
  - {label: "Español", field: language, pattern: "es"}
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - {label: "Draft?", name: "draft", widget: "boolean", default: true}
  - {label: "Título", name: "title", widget: "string", default: "{{slug}}"}
  - {label: "Âncora / Slug", name: "slug", widget: "string", required: false}
  - {label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss[Z]"}
  - {label: "Ordem no menu", name: "weight", widget: "number", value_type: "int", default: 0, min: 0, required: false}
  - {label: "Conteúdo", name: "body", widget: "markdown"}
  - {name: "layout", widget: "select", options: [ "analysis", "collaborate", "detailed", "faq", "results", "transparency", "about" ], required: false}
  - name: menu
    label: Menu
    widget: "object"
    required: false
    fields:
    - name: "header"
      label: "Header"
      widget: object
      required: false
      fields:
      - name: name
        widget: string
        required: false
    - name: "main"
      label: "Footer"
      widget: "object"
      required: false
      fields:
      - name: name
        widget: string
        required: false


- name: "analysis"
  label: "Análises"
  label_singular: "Análise"
  folder: "content/analysis"
  preview_path: "/analysis#{{slug}}"
  slug: "{{slug}}.{{language}}"
  format: frontmatter
  summary: "{{title}} ({{language}})"
  extension: "md"
  create: true
  view_filters:
  - {label: "Português", field: language, pattern: "pt"}
  - {label: "Español", field: language, pattern: "es"}
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - {label: "Draft?", name: "draft", widget: "boolean", default: true}
  - {label: "Título", name: "title", widget: "string", default: "{{slug}}"}
  - {label: "Âncora / Slug", name: "slug", widget: "string", required: false}
  - {label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss[Z]"}
  - {label: "Ordem", name: "weight", widget: "hidden", value_type: "int", default: 0, min: 0}
  - {label: "Show on home", name: "homepage", widget: "boolean", default: false, required: false}
  - {label: "Conteúdo", name: "body", widget: "markdown"}
  - label: "Favorito"
    name: "bookmark"
    widget: "object"
    collapsed: true
    fields:
    - {label: "Título", name: "title", widget: "string", default: "{{slug}}"}
    - {label: "Trecho", name: "excerpt", widget: "string"}
    - {label: "Imagem", name: "src", widget: "image"}
    - {label: "Descrição", name: "alt", widget: "string"}
    - {label: "Legenda", name: "caption", widget: "string"}
    - label: "Link"
      name: "link"
      default: ""
      widget: "string"
      pattern:
      - '^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)?'
      - "Use a valid URL"
  - {name: "layout", widget: "hidden", default: "none"}
  - {name: "type", widget: "hidden", default: "analysis"}


- name: bookmarks
  label: Favoritos
  folder: "content/bookmarks"
  preview_path: "{{dirname}}/{{filename}}.{{extension}}"
  slug: "{{slug}}.{{language}}"
  format: frontmatter
  summary: "{{title}} ({{language}})"
  extension: "md"
  create: true
  delete: true
  view_filters:
  - {label: "Português", field: language, pattern: "pt"}
  - {label: "Español", field: language, pattern: "es"}
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - {label: "Draft?", name: "draft", widget: "boolean", default: true}
  - {label: "Título", name: "title", widget: "string", default: "{{slug}}"}
  - {label: "Âncora / Slug", name: "slug", widget: "string", required: false}
  - {label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss[Z]"}
  - {label: "Ordem", name: "weight", widget: "hidden", value_type: "int", default: 0, min: 0}
  - {label: "Conteúdo", name: "body", widget: "markdown"}
  - name: "author"
    label: "Autor(es)"
    widget: "string"
  - name: "imageSrc"
    label: "Imagem (.svg)"
    widget: "image"
  - name: "Image description"
    label: "imageAlt"
    widget: "string"
    required: false
  - name: "link"
    default: ""
    label: "Link"
    widget: "string"
    required: false
    pattern:
    - '^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)?'
    - "Use a valid URL"
  - {name: "layout", widget: "hidden", default: "none"}
  - {name: "type", widget: "hidden", default: "bookmark"}


- name: "callToAction"
  label: "Chamadas"
  folder: "content/call-to-action"
  preview_path: "{{dirname}}/{{filename}}.{{extension}}"
  slug: "{{slug}}.{{language}}"
  format: frontmatter
  summary: "{{title}} ({{language}})"
  extension: "md"
  create: true
  delete: true
  view_filters:
  - {label: "Português", field: language, pattern: "pt"}
  - {label: "Español", field: language, pattern: "es"}
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - {label: "Draft?", name: "draft", widget: "boolean", default: true}
  - {label: "Título", name: "title", widget: "string", default: "{{slug}}"}
  - {label: "Âncora / Slug", name: "slug", widget: "string", required: false}
  - {label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss[Z]"}
  - {label: "Ordem", name: "weight", widget: "hidden", value_type: "int", default: 0, min: 0}
  - label: "Conteúdo"
    name: "body"
    widget: "markdown"
    required: false
  - name: "type"
    label: "type"
    widget: "hidden"
    default: "callToAction"
  - {name: "layout", widget: "hidden", default: "none"}


- name: "collaborate"
  label: "Chamadas a colaborar"
  folder: "content/collaborate"
  preview_path: "{{dirname}}/{{filename}}.{{extension}}"
  slug: "{{slug}}.{{language}}"
  format: frontmatter
  summary: "{{title}} ({{language}})"
  extension: "md"
  create: true
  delete: true
  view_filters:
  - {label: "Português", field: language, pattern: "pt"}
  - {label: "Español", field: language, pattern: "es"}
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - {label: "Draft?", name: "draft", widget: "boolean", default: true}
  - {label: "Título", name: "title", widget: "string", default: "{{slug}}"}
  - {label: "Âncora / Slug", name: "slug", widget: "string", required: false}
  - {label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss[Z]"}
  - {label: "Ordem", name: "weight", widget: "hidden", value_type: "int", default: 0, min: 0}
  - {label: "Conteúdo", name: "body", widget: "markdown"}
  - name: "type"
    label: "type"
    widget: "hidden"
    default: "collaborate"
  - {label: "Menus", name: "menu", widget: "select", options: [{ label: "Top", value: "header" }, { label: "Bottom", value: "main" }], required: false}
  - name: "imageSrc"
    label: "Imagem"
    widget: "image"
  - name: "bottomImageSrc"
    label: "Imagem inferior"
    widget: "image"
  - label: "Link"
    name: "link"
    default: ""
    widget: "string"
    pattern:
    - '^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)?'
    - "Use a valid URL"


- name: "faq"
  label: "Perguntas frequentes"
  label_singular: "Pergunta frequente"
  folder: "content/faq"
  preview_path: "/faq#{{slug}}"
  slug: "{{slug}}.{{language}}"
  format: frontmatter
  summary: "{{title}} ({{language}})"
  extension: "md"
  create: true
  view_filters:
  - {label: "Português", field: language, pattern: "pt"}
  - {label: "Español", field: language, pattern: "es"}
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - {label: "Draft?", name: "draft", widget: "boolean", default: true}
  - {label: "Título", name: "title", widget: "string", default: "{{slug}}"}
  - {label: "Âncora / Slug", name: "slug", widget: "string", required: false}
  - {label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss[Z]"}
  - {label: "Ordem", name: "weight", widget: "number", value_type: "int", default: 0, min: 0, required: false}
  - {label: "Conteúdo", name: "body", widget: "markdown"}
  - {name: "layout", widget: "hidden", default: "none"}
  - {name: "type", widget: "hidden", default: "faq"}


- name: "investigations"
  label: "Investigações"
  label_singular: "Investigação"
  folder: "content/investigations"
  preview_path: "/investigations#{{slug}}"
  slug: "{{slug}}.{{language}}"
  format: frontmatter
  summary: "{{title}} ({{language}})"
  extension: "md"
  create: true
  view_filters:
  - {label: "Português", field: language, pattern: "pt"}
  - {label: "Español", field: language, pattern: "es"}
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - {label: "Draft?", name: "draft", widget: "boolean", default: true}
  - {label: "Título", name: "title", widget: "string", default: "{{slug}}"}
  - {label: "Âncora / Slug", name: "slug", widget: "string", required: false}
  - {label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss[Z]"}
  - {label: "Conteúdo", name: "body", widget: "markdown", required: false}
  - name: "file"
    label: "Arquivo para download"
    widget: "file"
  - {label: "Ordem", name: "weight", widget: "number", value_type: "int", default: 0, min: 0, required: false}
  - {name: "layout", widget: "hidden", default: "none"}
  - {name: "type", widget: "hidden", default: "investigations"}
  - {label: "Show on home", name: "homepage", widget: "boolean", default: false, required: false}


- name: results
  label: "Seção de resultados"
  folder: "content/results"
  preview_path: "{{dirname}}/{{filename}}.{{extension}}"
  slug: "{{slug}}.{{language}}"
  format: frontmatter
  summary: "{{title}} ({{language}})"
  extension: "md"
  view_filters:
  - {label: "Português", field: language, pattern: "pt"}
  - {label: "Español", field: language, pattern: "es"}
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - {label: "Título", name: "title", widget: "string", default: "{{slug}}"}
  - {label: "Âncora / Slug", name: "slug", widget: "string", required: false}
  - {label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss[Z]"}
  - {label: "Ordem", name: "weight", widget: "hidden", value_type: "int", default: 0, min: 0}
  - {label: "Conteúdo", name: "body", widget: "markdown"}
  - name: "figure"
    widget: "object"
    fields:
    - name: "src"
      widget: file
      required: true
    - name: "caption"
      label: "Legenda"
      widget: "string"
    - name: "alt"
      label: "Descrição"
      widget: "string"
      required: true
  - {name: "layout", widget: "select", options: [ "results", "none" ]}


- name: "transparency"
  label: "Transparência"
  folder: "content/transparency"
  preview_path: "/transparency#{{slug}}"
  slug: "{{slug}}.{{language}}"
  format: frontmatter
  summary: "{{title}} ({{language}})"
  extension: "md"
  create: true
  view_filters:
  - {label: "Português", field: language, pattern: "pt"}
  - {label: "Español", field: language, pattern: "es"}
  fields:
  - {label: "Idioma", name: "language", widget: "select", options: ["es", "pt"]}
  - {label: "Draft?", name: "draft", widget: "boolean", default: true}
  - {label: "Título", name: "title", widget: "string", default: "{{slug}}"}
  - {label: "Âncora / Slug", name: "slug", widget: "string", required: false}
  - {label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss[Z]"}
  - {label: "Ordem", name: "weight", widget: "hidden", value_type: "int", default: 0, min: 0}
  - name: "intro"
    label: "Introdução"
    widget: "text"
    required: false
  - {label: "Conteúdo", name: "body", widget: "markdown"}
  - {label: "Show on home", name: "homepage", widget: "boolean", default: false, required: false}
  - {label: "Show on transparency", name: "transparency", widget: "boolean", default: false}
  - {name: "layout", widget: "hidden", default: "none"}


# - name: supporters
#   label: "Apoiadores"
#   slug: "{{slug}}.{{language}}"
#   format: frontmatter
#   summary: "{{title}} ({{language}})"
#   extension: "md"
#   files:
#   - name: "supporters"
#     label: "Apoiadores"
#     file: "data/supporters.json"
#     fields:
#     - name: "title"
#       label: "Título"
#       widget: "string"
#     - name: "image"
#       label: "Logo (svg)"
#       widget: "image"
#     - name: "url"
#       label: "url"
#     - name: "weight"
#       value_type: "int"
#       label: "Ordem"
#       widget: "hidden"
#       default: 1
#       min: 0
