backend:
  name: github
  # @see https://www.netlifycms.org/docs/test-backend/
  # name: test-repo
  branch: dev # Branch to update (optional; defaults to master)
  repo: AppCivico/pegabot
  site_domain: dev.pegabot.com.br
  base_url: https://api.netlify.com
  auth_endpoint: auth
  squash_merges: true
  api_root: https://api.github.com
media_folder: "content/uploads"
public_folder: "uploads"
locale: "pt"
sortableFields: ["commit_date", "title", "commit_author", "language"]
logo_url: /images/logotype--no-text.png
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
- name: "analysis-pt"
  label: "Análises"
  label_singular: "Análise"
  folder: "content/portuguese/analysis"
  slug: "{{slug}}"
  preview_path: "/analysis#{{slug}}"
  create: true
  extension: md
  fields:
  - name: "title"
    label: "Título"
    widget: "string"
  - name: "file"
    label: "Arquivo para download"
    widget: "file"
  - name: "slug"
    label: "Âncora"
    widget: "string"
    required: false
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"
  - label: "Favorito"
    name: "bookmark"
    widget: "object"
    collapsed: true
    fields:
    - {label: "Título", name: "title", widget: "string"}
    - {label: "Trecho", name: "excerpt", widget: "string"}
    - {label: "Imagem", name: "src", widget: "image"}
    - {label: "Descrição", name: "alt", widget: "string"}
    - {label: "Legenda", name: "caption", widget: "string"}
    - label: "Link"
      name: "link"
      widget: "string"
      pattern:
      - '^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)?'
      - "Use a valid URL"

- name: "analysis-es"
  label: "Análises"
  label_singular: "Análise"
  folder: "content/spanish/analysis"
  slug: "{{slug}}"
  preview_path: "/analysis#{{slug}}"
  create: true
  extension: md
  fields:
  - name: "title"
    label: "Título"
    widget: "string"
  - name: "file"
    label: "Arquivo para download"
    widget: "file"
  - name: "slug"
    label: "Âncora"
    widget: "string"
    required: false
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"
  - label: "Favorito"
    name: "bookmark"
    widget: "object"
    collapsed: true
    fields:
    - {label: "Título", name: "title", widget: "string"}
    - {label: "Trecho", name: "excerpt", widget: "string"}
    - {label: "Imagem", name: "src", widget: "image"}
    - {label: "Descrição", name: "alt", widget: "string"}
    - {label: "Legenda", name: "caption", widget: "string"}
    - label: "Link"
      name: "link"
      widget: "string"
      pattern:
      - '^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)?'
      - "Use a valid URL"

- name: bookmarks-pt
  label: Favoritos
  slug: "{{slug}}"
  folder: "content/portuguese/bookmarks"
  create: true
  delete: true
  fields:
  - name: "title"
    label: "Título"
    widget: "hidden"
    default: "{{slug}}"
  - name: "author"
    label: "Autor(es)"
    widget: "string"
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "image"
    label: "Imagem (.svg)"
    widget: "image"
  - label: "Link"
    name: "link"
    widget: "string"
    required: false
    pattern:
    - '^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)?'
    - "Use a valid URL"

- name: bookmarks-es
  label: Favoritos
  slug: "{{slug}}"
  folder: "content/spanish/bookmarks"
  create: true
  delete: true
  fields:
  - name: "title"
    label: "Título"
    widget: "hidden"
    default: "{{slug}}"
  - name: "author"
    label: "Autor(es)"
    widget: "string"
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "image"
    label: "Imagem (.svg)"
    widget: "image"
  - label: "Link"
    name: "link"
    widget: "string"
    required: false
    pattern:
    - '^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)?'
    - "Use a valid URL"

- name: "callToAction-pt"
  label: "Chamadas"
  folder: "content/portuguese/call-to-action"
  create: true
  delete: true
  slug: "{{slug}}"
  fields:
  - name: "title"
    label: "Título"
    widget: "string"
    tagname: "h3"
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "type"
    label: "type"
    widget: "hidden"
    default: "callToAction"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"
  - name: "weight"
    label: "Ordem"
    widget: "number"
    default: 1
    valueType: "int"
    min: 0

- name: "callToAction-es"
  label: "Chamadas"
  folder: "content/spanish/call-to-action"
  create: true
  delete: true
  slug: "{{slug}}"
  fields:
  - name: "title"
    label: "Título"
    widget: "string"
    tagname: "h3"
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "type"
    label: "type"
    widget: "hidden"
    default: "callToAction"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"
  - name: "weight"
    label: "Ordem"
    widget: "number"
    default: 1
    valueType: "int"
    min: 0

- name: "collaborate-pt"
  label: "Chamadas a colaborar"
  folder: "content/portuguese/collaborate"
  create: true
  delete: true
  slug: "{{slug}}"
  fields:
  - name: "title"
    label: "Título"
    widget: "string"
    tagname: "h3"
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "type"
    label: "type"
    widget: "hidden"
    default: "collaborate"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"
  - name: "weight"
    label: "Ordem"
    widget: "number"
    default: 1
    valueType: "int"
    min: 0
  - name: "imageSrc"
    label: "Imagem"
    widget: "image"
  - name: "bottomImageSrc"
    label: "Imagem inferior"
    widget: "image"
  - label: "Link"
    name: "link"
    widget: "string"
    pattern:
    - '^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)?'
    - "Use a valid URL"

- name: "collaborate-es"
  label: "Chamadas a colaborar"
  folder: "content/spanish/collaborate"
  create: true
  delete: true
  slug: "{{slug}}"
  fields:
  - name: "title"
    label: "Título"
    widget: "string"
    tagname: "h3"
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "type"
    label: "type"
    widget: "hidden"
    default: "collaborate"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"
  - name: "weight"
    label: "Ordem"
    widget: "number"
    default: 1
    valueType: "int"
    min: 0
  - name: "imageSrc"
    label: "Imagem"
    widget: "image"
  - name: "bottomImageSrc"
    label: "Imagem inferior"
    widget: "image"
  - label: "Link"
    name: "link"
    widget: "string"
    pattern:
    - '^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)?'
    - "Use a valid URL"

- name: "faq-pt"
  label: "Perguntas frequentes"
  label_singular: "Pergunta frequente"
  folder: "content/portuguese/faq"
  # identifier_field: "slug"
  slug: "{{slug}}"
  preview_path: "/faq#{{slug}}"
  create: true
  extension: md
  fields:
  - name: "title"
    label: "Título"
    widget: "string"
  - name: "slug"
    label: "Âncora"
    widget: "string"
    required: false
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"

- name: "faq-es"
  label: "Perguntas frequentes"
  label_singular: "Pergunta frequente"
  folder: "content/spanish/faq"
  # identifier_field: "slug"
  slug: "{{slug}}"
  preview_path: "/faq#{{slug}}"
  create: true
  extension: md
  fields:
  - name: "title"
    label: "Título"
    widget: "string"
  - name: "slug"
    label: "Âncora"
    widget: "string"
    required: false
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"

- name: "investigations-pt"
  label: "Investigações"
  label_singular: "Investigação"
  folder: "content/portuguese/investigations"
  slug: "{{slug}}"
  preview_path: "/investigations#{{slug}}"
  create: true
  extension: md
  fields:
  - name: "title"
    label: "Título"
    widget: "string"
  - name: "file"
    label: "Arquivo para download"
    widget: "file"
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"

- name: "investigations-es"
  label: "Investigações"
  label_singular: "Investigação"
  folder: "content/spanish/investigations"
  slug: "{{slug}}"
  preview_path: "/investigations#{{slug}}"
  create: true
  extension: md
  fields:
  - name: "title"
    label: "Título"
    widget: "string"
  - name: "file"
    label: "Arquivo para download"
    widget: "file"
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"

- name: "pages-pt"
  label: "Páginas"
  folder: "content/portuguese"
  slug: "{{slug}}"
  preview_path: "/{{slug}}"
  create: true
  extension: md
  fields:
  - name: "title"
    label: "Título"
    widget: "string"
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"

- name: "pages-es"
  label: "Páginas"
  folder: "content/spanish"
  slug: "{{slug}}"
  preview_path: "/{{slug}}"
  create: true
  extension: md
  fields:
  - name: "title"
    label: "Título"
    widget: "string"
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"

- name: results-pt
  label: "Seção de resultados"
  folder: "content/portuguese/results"
  extension: md
  slug: "{{slug}}"
  fields:
  - name: "title"
    label: "Título"
    widget: "string"
  - name: "figure"
    widget: "object"
    fields:
    - name: "src"
      widget: file
      required: true
    - name: "caption"
      label: "Legenda"
      widget: "string"
    - name: "alt"
      label: "Descrição"
      widget: "string"
      required: true
  - name: "weight"
    label: "Ordem"
    default: 0

- name: results-es
  label: "Seção de resultados"
  folder: "content/spanish/results"
  extension: md
  slug: "{{slug}}"
  fields:
  - name: "title"
    label: "Título"
    widget: "string"
  - name: "figure"
    widget: "object"
    fields:
    - name: "src"
      widget: file
      required: true
    - name: "caption"
      label: "Legenda"
      widget: "string"
    - name: "alt"
      label: "Descrição"
      widget: "string"
      required: true
  - name: "weight"
    label: "Ordem"
    default: 0

- name: supporters-pt
  label: "Apoiadores"
  slug: "{{slug}}"
  files:
  - name: "supporters"
    label: "Apoiadores"
    file: "data/pt/supporters.json"
    fields:
    - name: "title"
      label: "Título"
      widget: "string"
    - name: "image"
      label: "Logo (svg)"
      widget: "image"
    - name: "url"
      label: "url"
    - name: "weight"
      label: "Ordem"
      default: 0

- name: supporters-es
  label: "Apoiadores"
  slug: "{{slug}}"
  files:
  - name: "supporters"
    label: "Apoiadores"
    file: "data/es/supporters.json"
    fields:
    - name: "title"
      label: "Título"
      widget: "string"
    - name: "image"
      label: "Logo (svg)"
      widget: "image"
    - name: "url"
      label: "url"
    - name: "weight"
      label: "Ordem"
      default: 0

- name: "transparency-pt"
  label: "Transparência"
  folder: "content/portuguese/transparency"
  slug: "{{slug}}"
  preview_path: "/transparency#{{slug}}"
  create: true
  extension: md
  fields:
  - name: "title"
    label: "Título"
    widget: "string"
  - name: "slug"
    label: "Âncora"
    widget: "string"
    required: false
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"

- name: "transparency-es"
  label: "Transparência"
  folder: "content/spanish/transparency"
  slug: "{{slug}}"
  preview_path: "/transparency#{{slug}}"
  create: true
  extension: md
  fields:
  - name: "title"
    label: "Título"
    widget: "string"
  - name: "slug"
    label: "Âncora"
    widget: "string"
    required: false
  - name: "date"
    label: "Data"
    widget: "datetime"
    format: "YYYY-MM-DDTHH:mm:ss[Z]"
  - name: "body"
    label: "Conteúdo"
    widget: "markdown"
